version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DSN=host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable
    ports:
      - "8080:8080"
    restart: always

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users