version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MYSQL_DSN="root:password@tcp(mysql:3306)/users"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"